# Generated by Django 3.0.4 on 2020-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hato_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinfo',
            name='animal_url',
            field=models.TextField(default=''),
        ),
    ]
