# Generated by Django 3.0.4 on 2020-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hato_app', '0002_animalinfo_animal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinfo',
            name='animal_wiki',
            field=models.TextField(default=''),
        ),
    ]
